DROP TABLE IF EXISTS CURRENCY_NAME_CONTRAST;

CREATE TABLE CURRENCY_NAME_CONTRAST (
    CODE VARCHAR(10) PRIMARY KEY,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CHINESE_NAME VARCHAR(31) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL,
    MODIFY_TIME TIMESTAMP NOT NULL
);